create TABLE ORDERS (
  ID VARCHAR(32) unique NOT NULL,
  STATUS varchar(10) NOT NULL,
  TOTAL_PRICE DECIMAL NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

create TABLE ORDER_ITEMS (
  ID VARCHAR(32) unique NOT NULL,
  ORDER_ID VARCHAR(32) NOT NULL,
  PRODUCT_ID VARCHAR(32) NOT NULL,
  COUNT DECIMAL NOT NULL,
  PRICE DECIMAL NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
